### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Roken120** [iiegor/slither-go#1]
Hello please help to work your slither-go because i install go and gopm an error
[Root@Server ] : gopm run server.go
[GOPM] 04-18 23:37:54 [FATAL] package not installed: github.com/gorilla/websocket @ commit:e2e3d84
Please help me or send a command for work this
sorry for my bad english

**Comment by iiegor** [comment]
Did you run `gopm install`? The output says that the package `gorilla/websocket` is not installed.

Anyway, this is in a very early stage of development and is focused on performance, if you want something more updated check my other repository, [iiegor/slither](https://github.com/iiegor/slither).

**Comment by Roken120** [comment]
I search a site emulator for Create m'y private server Please hep me i need command for centos or other
Thank you
