### ISSUE TITLE
gopm install error

### ISSUE THREAD

**Issue by chenny** [iiegor/slither-go#2]
[GOPM] 08-24 17:19:01 [FATAL] package not installed: github.com/gorilla/websocket @ commit:e2e3d84
<img width="827" alt="qq20160918-1" src="https://cloud.githubusercontent.com/assets/883329/18614463/b7ca0d08-7dc1-11e6-8c45-cf38f84a6726.png">

**Comment by iiegor** [comment]
> package not installed

Just install the dependencies by running: `gopm install`

**Comment by chenny** [comment]
slither-go Roadmap ? is Cancelled? Late also update it?
